jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: CHRIS_PUURI@HAKKODA.IO
      role: "{{ env_var('SNOWFLAKE_ROLE') | as_text }}"

      # SSO config -- The three following fields are REQUIRED
      authenticator: hakkoda.okta.com
      username: chris_puuri
      password: "{{ env_var('SNOWFLAKE_PASSWORD') | as_text }}"
      
      database: HAKKODA_EDW_DEV
      warehouse: HAKKODA_EDW_WH
      schema: dbt_cpuuri
      threads: 8
      client_session_keep_alive: False

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false      
